### ISSUE TITLE
"training_data table not found" Part 5

### ISSUE THREAD

**Issue by ortega-01** [Nomiizz/KryptoOracle#12]
Hi! Thank you guys for the work you've done, if you can help me with some issues I would really appreciate it. 

I'm having issues with this section:
![image](https://user-images.githubusercontent.com/60853550/164800542-df591035-876e-4798-b20e-a5176ad1baf0.png)
Where are the tables created?

**Comment by mshubhankar** [comment]
Hey! 
The tables are created on Hive using PySpark. 
You should be able to replicate the database by installing PySpark and following each step line by line on the notebook.

**Comment by ortega-01** [comment]
Ok thanks so much for getting back to me! Which version of python is
section 5 and 6 using? I used 3.8 and had a change a few things so maybe
that’s why it wasn’t working

**Comment by mshubhankar** [comment]
I believe it should be Python 3.6

**Comment by ortega-01** [comment]
Ok thank you!
