### ISSUE TITLE
[BUG] Outdated Access Token

### ISSUE THREAD

**Issue by MohammadForouhesh** [Nomiizz/KryptoOracle#13]
The Twitter API access tokens provided in this repository is outdated and the code doesn't work. Is there a way to provide an updated version.

**Comment by mshubhankar** [comment]
Indeed the API access is outdated. 
You are supposed use your own access token for use of this repository. 
You can get yourself one [here](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens)
