### ISSUE TITLE
stream_crypto.js file missing?

### ISSUE THREAD

**Issue by StevenBeyen** [Nomiizz/KryptoOracle#6]
Hi,

Thanks a lot for this amazing work!

I have a small request: by the end of notebook 4 you reference a file named 'streamer/stream_crypto.js' that is not present in the repository and is needed to run the script below.
Could you also upload this script?

Kind regards,

Steven

**Comment by mshubhankar** [comment]
Hey Steven,
That part of the code is for aesthetics and while testing we skipped that part.
Thanks for noticing this though.
I have added the required file. Hope it works!

**Comment by mshubhankar** [comment]
Fixed.
