### ISSUE TITLE
Couldn't find file "streamdata.txt" in code 06_Realtime_Time_Series.

### ISSUE THREAD

**Issue by MohammadrezaMirzaei** [Nomiizz/KryptoOracle#9]
Hi I didn't find the file "streamdata.txt" in code "06_Realtime_Time_Series". what should I do. 
I had some problems in the last part of file  "04_TwitterSentimentAndCryptocurrencies" in running stream.open().

**Comment by mshubhankar** [comment]
Hi! 
The streamdata.txt is a file which stores the past minutes stream data. At the start, the file should be blank.
Try creating the file using `touch streamdata.txt` and running the 06_Realtime_Time_Series file. 

Sorry, I don't understand completely. Could you please point to the line number which is causing the problem in 04_TwitterSentimentAndCryptocurrencies?

**Comment by pandey-prakhar** [comment]
Hey, I am doing this project and I am having issues with Notebook 03_CryptoCurrencyExtraction, Here it is showing KeyError: 'time', I am attaching a screenshot for reference.
Also, I am not able to see notebook 5. so where can I get that?
![n3error](https://user-images.githubusercontent.com/87385842/159755603-0ba4b4c1-ea9d-4df3-817f-b631ad1f382e.png)
![N3errorCodeBlock](https://user-images.githubusercontent.com/87385842/159755607-b9cbcc02-1861-4026-83d9-528fbbf566d6.png)

**Comment by mshubhankar** [comment]
@pandey-prakhar  : I'm not sure why you don't have the 'time' column in your dataframe. That should be pulled directly from the URL using the `get_data_minutely()` function. Maybe try debugging by printing the dataframe and figure out what's going wrong?
An example URL is this : [crypto data]( https://min-api.cryptocompare.com/data/histominute?fsym=BTC&tsym=USD&limit=2000&toTs=-1&extraParams=HES_SO_master_crypto_analysis)

We don't have any results on our paper from Notebook5.

**Comment by mshubhankar** [comment]
Solved with PR#10
